resources:
  jobs:
    New_Job_Feb_06_2026_04_35_PM:
      name: New Job Feb 06, 2026, 04:35 PM
      tasks:
        - task_key: GBDP_backfill
          spark_python_task:
            python_file: /Repos/eric.t.seppanen@gmail.com/GBDP/dbx_entry.py
            parameters:
              - backfill
              - --start
              - 2004-05-18
              - --end
              - 2004-11-1
              - --sources
              - configs/sources.yaml
              - --force
              - --storage-format
              - delta
              - --bronze-root
              - dbfs:/Volumes/gbdp/bronze_gbdp/bronze_vol/gbdp/bronze
              - --silver-root
              - dbfs:/Volumes/gbdp/silver_gbdp/silver_vol/gbdp/silver
              - --gold-root
              - dbfs:/Volumes/gbdp/gold_gbdp/gold_vol/gbdp/gold
              - --manual-root
              - dbfs:/Volumes/gbdp/bronze_gbdp/bronze_vol/gbdp/manual
              - --retries
              - "2"
              - --retry-delay
              - "5"
              - --chunk
              - month
              - --uc-catalog
              - gbdp
              - --uc-bronze-schema
              - bronze_gbdp
              - --uc-silver-schema
              - silver_gbdp
              - --uc-gold-schema
              - gold_gbdp
              - --uc-mode
              - managed
          environment_variables: {}
          email_notifications:
            on_success:
              - eric.t.seppanen@gmail.com
            on_failure:
              - eric.t.seppanen@gmail.com
          environment_key: Default
      queue:
        enabled: true
      environments:
        - environment_key: Default
          spec:
            environment_version: "4"
      performance_target: PERFORMANCE_OPTIMIZED
